name: Test SSH

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          ssh-keyscan -H ${{ secrets.DEV_SERVER }} >> ~/.ssh/known_hosts
          ssh-keyscan -H ${{ secrets.PROD_SERVER }} >> ~/.ssh/known_hosts

      - name: Test SSH Dev
        run: ssh ${{ secrets.DEV_SERVER }} "echo ✅ Connected to Dev EC2"

      - name: Test SSH Prod
        run: ssh ${{ secrets.PROD_SERVER }} "echo ✅ Connected to Prod EC2"
