- name: Setup SSH
  run: |
    mkdir -p ~/.ssh
    echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
    chmod 600 ~/.ssh/id_rsa

    # Add Dev and Prod fingerprints to known_hosts
    ssh-keyscan -H $(echo ${{ secrets.DEV_SERVER }} | cut -d@ -f2) >> ~/.ssh/known_hosts
    ssh-keyscan -H $(echo ${{ secrets.PROD_SERVER }} | cut -d@ -f2) >> ~/.ssh/known_hosts
